services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
     - "27017:27017"
    volumes:
     - mongodb_data:/data/db
     - ./machine-learning-client/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro #instantiate dummmy data
    networks:
      - app-network
  ml-client:
    build:
      context: ./machine-learning-client
    ports:
      - "5002:5001"
    env_file:
      - ./machine-learning-client/.env
    networks:
      - app-network
    depends_on:
      - mongodb
  web-app:
    build:
      context: ./web-app
    ports:
      - "5001:5000"
    env_file:
      - ./web-app/.env
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data: {}
networks:
  app-network: {}