name: Machine Learning Client CI

on:
  push:
    paths:
      - 'machine_learning_client/**'
  pull_request:
    paths:
      - 'machine_learning_client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ml-client-test ./machine_learning_client

      - name: Run tests inside container
        run: |
          docker run --rm ml-client-test pytest