name: Machine Learning Client CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env.example to .env
        run: cp web-app/.env.example web-app/.env

      - name: Build Docker image
        run: |
          docker build -t web-app-test ./web-app

      - name: Run tests inside container with env vars
        run: |
          docker run --rm --env-file web-app/.env web-app-test pytest
